version: '3.8'
services:
  cryptcoin:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: uDr4KjGcpEm6N5F3BqhxAT2
      POSTGRES_PASSWORD: 12xt6h4fWf4QL9WiP5syZ887S8Si54giDizdB8L685aBiBkBVaW87MS3bWc22ba3L9YT32
      POSTGRES_DB: cW76664NDPkmc2
    networks:
      - CRY
  test-db:
    image: postgres:13
    ports:
      - 5434:5434
    environment:
      POSTGRES_USER: uDr4KjGcpEm6N5F3BqhxAT
      POSTGRES_PASSWORD: 12xt6h4fWf4QL9WiP5syZ887S8Si54giDizdB8L685aBiBkBVaW87MS3bWc22ba3L9YT3
      POSTGRES_DB: cW76664NDPkmc
    networks:
      - CRY
networks:
  CRY:
    external: true
